### PR TITLE
Fixed grammar again

### PR DESCRIPTION
**Pull request by archisha69**
Welp

### CODE REVIEW

**Comment by notsniped** [comment]
Nothing wrong with the initial grammar

**Comment by archisha69** [comment]
> Nothing wrong with the initial grammar

no because of the "s"

**Comment by archisha69** [comment]
> Nothing wrong with the initial grammar

its the same thing that i did before how is it ok

**Comment by notsniped** [comment]
```py
@slash.slash(
    name='work',
    description='Works for a 30-minute shift and earn cash.'
)
```
The bot is supposed to mimic RP (roleplay). The bot isn't supposed to "hunt" for you, its a command given to make **you** hunt.

**Comment by archisha69** [comment]
> ```py
> @slash.slash(
>     name='work',
>     description='Works for a 30-minute shift and earn cash.'
> )
> ```
> The bot is supposed to mimic RP (roleplay). The bot isn't supposed to "hunt" for you, its a command given to make **you** hunt.

bruh

**Comment by notsniped** [comment]
Stale branch, so I am deleting it.

**Pull request closed without merging**
