### PR TITLE
Fix exception-handling builtins

### PR DESCRIPTION
**Pull request by archisha69**
why tf is raise and except becoming functions notsniped

### CODE REVIEW

**Comment by notsniped** [comment]
and its funny how i went from javascript to python

**Comment by archisha69** [comment]
> and its funny how i went from javascript to python

does that even work

**Review by notsniped — APPROVED** [review]
Small debloat, initial source does not affect functioning of the program, but removing `()` will free up a tiny bit of space

**Comment by notsniped** [comment]
> > and its funny how i went from javascript to python
> 
> does that even work

yes

**Comment by archisha69** [comment]
cuz archie and i saw that and went "wtf is that"

**Comment by archisha69** [comment]
> > > and its funny how i went from javascript to python
> > 
> > 
> > does that even work
> 
> yes

wtf

**Comment by notsniped** [comment]
> cuz archie and i saw that and went "wtf is that"

its a person coding in python, former js coder

**Comment by archisha69** [comment]
> > cuz archie and i saw that and went "wtf is that"
> 
> its a person coding in python, former js coder

.

**Comment by notsniped** [comment]
> > > cuz archie and i saw that and went "wtf is that"
> > 
> > 
> > its a person coding in python, former js coder
> 
> .

So you basically debloated the code, no functioning of the actual client was altered

**Pull request merged**
