### PR TITLE
Add binoculars in shop config file

### PR DESCRIPTION
**Pull request by archisha69**
May add more later, out of ideas

### CODE REVIEW

**Review by notsniped — CHANGES_REQUESTED** [review]
Key name "available" should be set to "true". After all, it's a purchasable item. Right?

**Comment by archisha69** [comment]
> Key name "available" should be set to "true". After all, it's a purchasable item. Right?

no because its not comfirmed like those in shop.json

**Comment by notsniped** [comment]
Ok. I will open them as soon as i work on the feature.

**Review by notsniped — APPROVED** [review]
PR had been reconsidered

**Pull request merged**
