### PR TITLE
Add lootboxes in catalog

### PR DESCRIPTION
**Pull request by archisha69**
Open cmd

### CODE REVIEW

**Comment by archisha69** [comment]
> "type" isn't a valid key name, it's actually called "stylized name". I could change this, but for now i can confirm that i won't be working on it.

No it's a separated thing, not shop.json

**Comment by archisha69** [comment]
> "type" isn't a valid key name, it's actually called "stylized name". I could change this, but for now i can confirm that i won't be working on it.

But anyway it's fine

**Comment by notsniped** [comment]
> > "type" isn't a valid key name, it's actually called "stylized name". I could change this, but for now i can confirm that i won't be working on it.
> 
> No it's a separated thing, not shop.json

There is no support for that key in the client

**Comment by archisha69** [comment]
> > > "type" isn't a valid key name, it's actually called "stylized name". I could change this, but for now i can confirm that i won't be working on it.
> > 
> > No it's a separated thing, not shop.json
> 
> There is no support for that key in the client

anyway, **i dont care abt this sh*t**

**Comment by notsniped** [comment]
Okay, I will fix the changes myself.

**Comment by notsniped** [comment]
> > "type" isn't a valid key name, it's actually called "stylized name". I could change this, but for now i can confirm that i won't be working on it.
> 
> No it's a separated thing, not shop.json

I renamed the keys and moved another copy of them to shop.json

**Review by notsniped — APPROVED** [review]
Loot boxes have been added to `shop.json`, as well as an additional copy in `config/data/lootbox.json`.

**Comment by notsniped** [comment]
`/use` command will be added later

**Pull request merged**
