### PR TITLE
Merge this, just do it.

### PR DESCRIPTION
**Pull request by archisha69**
.

### CODE REVIEW

**Comment by notsniped** [comment]
arc linuk

**Review by notsniped — APPROVED** [review]
I use arch btw

**Comment by archisha69** [comment]
> arc linuk

Arc inuk

**Comment by notsniped** [comment]
@thatOneArchUser waiting for approval 👍

**Comment by notsniped** [comment]
Never mind he won't give a sh*t, I'll just merge it.

**Comment by archisha69** [comment]
> Never mind he won't give a sh*t, I'll just merge it.

LMAO just told ya to merge it, the title said so

**Pull request merged**
