### PR TITLE
Group imports into single line

### PR DESCRIPTION
**Pull request by notsniped**
A part of Pull Request: #77

### CODE REVIEW

**Comment by notsniped** [comment]
@thatOneArchUser

**Comment by thatOneArchUser** [comment]
i might debloat more later cuz im trying to install some stuff rn

**Comment by notsniped** [comment]
Alright lmk when you're ready

**Comment by notsniped** [comment]
Not ready yet?

**Comment by notsniped** [comment]
Almost a week since last response, I am force-merging this PR.

**Pull request merged**
